accounts/urls.py
from django.contrib import admin
from django.urls import path,re_path
from .import views

app_name = 'accounts'

urlpatterns =[
    re_path(r'^registration/$', views.registration_view, name="registration"),
    re_path(r'^registration/authorization/$', views.authorization_view, name="authorization")
]

apptoweb/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name="index"),
    re_path(r'^accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
# Create your models here.


class CustomUserManger(BaseUserManager):
    def create_user(self,email,firstname,lastname,auth_number,password):

        if not email:
            raise ValueError('Email is required')
        user = self.model( email = self.normalize_email(email),
                           firstname = firstname,
                           lastname = lastname,
                           auth_number = auth_number,)
        # TODO check to make sure password is encrypted with Bcrypt
        user.set_password(password)
        user.save(using=self._db)
        return user
    # COMPLETED create create_superuser here

    def create_superuser(self,email,firstname,lastname,auth_number,password):

        if not email:
            raise ValueError('Email is required')
        user = self.model( email = self.normalize_email(email),
                           firstname = firstname,
                           lastname = lastname,
                           auth_number = auth_number,)
        # TODO check to make sure password is encrypted with Bcrypt
        user.set_password(password)
        user.is_admin = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser):

    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    email = models.EmailField(verbose_name='email address',max_length=255,unique=True)
    auth_number = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_authorized = models.BooleanField(default=False) # becomes True when user confirm Auth code

    objects = CustomUserManger()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['firstname','lastname','auth_number']

    """
    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    # Review snippet below
    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin
    """

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm,AuthenticationForm
from django import forms
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    """
    def __init__(self, *args,**kargs):
        super(CustomUserCreationForm, self).__init__(*args, **kargs)
        del self.fields['username']
    """
    class Meta:
        model = CustomUser
        fields = (
            'firstname',
            'lastname',
            'email',
        )


class CustomUserAuthorizationForm(forms.Form):
    """
    model = CustomUser
    fields = (
        'auth_number'
    )"""

    auth_number = forms.CharField(label='Authorization Number', max_length=30)
    email = forms.EmailField(initial='testing', widget=forms.HiddenInput())

accounts/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from .models import CustomUser
from .import forms

# Create your views here.

User = get_user_model()


def registration_view(request):
    if request.method == 'POST':
        form = forms.CustomUserCreationForm(request.POST)
        if form.is_valid():

            user = form.save(commit=False)
            # TODO generate &/ send user authorization code
            user.auth_number = 12345
            user.save()
            # COMPLETED register & login user
            login(request, user)
            return redirect('accounts:authorization')
    else:
        form = forms.CustomUserCreationForm()
    return render(request, 'accounts/registration.html', {'form': form})


@login_required(login_url="/accounts/registration/")
def authorization_view(request):
    # TODO return 1 uppon success 0 if fail
    if request.method == 'POST':
        form = forms.CustomUserAuthorizationForm(request.POST)

        if form.is_valid():
            form_auth_number = form.cleaned_data['auth_number']
            form_email = form.cleaned_data['email']

            # Get user in DB with request email
            user = User.objects.get(email=form_email)

            # Check if user is already authorized
            if user.is_authorized:
                # return HttpResponse('User Already Authorized')
                return JsonResponse({'success': 1})
            else:
                if form_auth_number == user.auth_number:

                    # authorize the user
                    user.is_authorized = True
                    user.save()
                    # return HttpResponse('Now Authorized')
                    return JsonResponse({'success': 1})
                    # test line | return HttpResponse(user.is_authorized) returned True
                else:
                    # return HttpResponse('Error no match') # Redirect user to auth page
                    return JsonResponse({'success': 0})
            # test line | return HttpResponse(form_email)

        # test line | return HttpResponse('Request came in')
    else:
        curr_user_email = request.user.email
        form = forms.CustomUserAuthorizationForm(initial={'email': curr_user_email})
        return render(request, 'accounts/authorization.html', {'form': form})

apptoweb/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    #return HttpResponse('Index view func calling')
    return render(request,'index.html')

accounts/templates/accounts/authorization.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Auth View</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<style>
    input[type="submit"]{
        cursor:pointer;
    }
</style>
<body>
    <h1>Authorization</h1>
    <p>for: {{user.firstname}}</p>
    <p>Expected Auth_Number: {{user.auth_number}}</p>

    <form id="authorization_form" method="post">
        {% csrf_token %}
        {{form}}
        <!--
        <label for="a_number">Authorization Number:</label>
        <input id="a_number" name="auth_number" type="text">

        <input type="hidden" name="email" value="{{user.email}}">
        -->
        <input type="submit" id="authorize" value="Next">
    </form>
    <script>
        $(document).on('submit','#authorization_form', function(event){
            console.log('inside form submit')
            event.preventDefault();
            alert("Form script triggered");
            console.log("form default prevented...");
            console.log("above ajax block");
            $.ajax({
                console.log('inside ajax snippet');
                url: "{% url 'accounts:authorization' %}",
                dataType: "json",
                method: "POST",
                data:{auth_number: auth_number,email:email},
                success:function(data){
                    return data;
                }
            });
        });
    </script>
</body>
</html>

accounts/templates/accounts/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Authorization</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<style>
    form div{
        padding: 5px;
        margin: 10px;
    }
    form div label{
        display: block;
    }
    form div input[type="submit"]{
        cursor: pointer;
    }
</style>
<body>
    <h1>Registration Page</h1>
    <form id="auth_form" method="post">
        {% csrf_token %}
        {{ form }}
        <!--
        <div>
            <label for="firstname">First Name:</label>
            <input type="text" id="firstname" name="firstname">
        </div>
        <div>
            <label for="lastname">Last Name:</label>
            <input type="text" id="lastname" name="lastname">
        </div>
        <div>
            <label for="email">Email:</label>
            <input type="email" id="email" name="email">
        </div>
        <div>
            <label for="password">Password:</label>
        <input type="password" id="password" name="password">
        </div>-->
        <!-- TODO create a re-enter password field -->
        <!--
        <div>
            <label for="auth_number">Authorization #:</label>
            <input type="text" id="auth_number" name="auth_number">
        </div>
        -->
        <div>
            <input type="submit" id="register" value="Register">
        </div>
    </form>
    <!--
    // TODO CREATE ajax.py -->
    <script>
        $(document).on('submit','#auth_form',function(event){
            event.preventDefault();
            alert("Default prevented");
            console.log("form default prevented...");
            console.log("above ajax block");
            $.ajax({
                console.log("inside ajax method");
                url: "{% url 'accounts:registration' %}",
                method:"POST",
                data:{firstname: firstname, lastname:lastname,email:email,password:password,auth_number:auth_number},
                dataType:"json",
                success:function(data)
                {
                    //do something
                    return data;
                }
            });
        });
    </script>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
</head>
<body>
    <h1>Welcome Home</h1>
    <a href="{% url 'accounts:registration' %}">Register</a>
</body>
</html>